hardware: gpu
dcn_data_parallelism: 7
dcn_fsdp_parallelism: 32
ici_fsdp_parallelism: 8
per_device_batch_size: 1
eval_per_device_batch_size: 1
max_target_length: 8192
learning_rate: 0.001
model_name: llama3.1-405b
tokenizer_type: huggingface
tokenizer_path: /workspace/assets/mistral/tokenizer
dataset_type: c4_mlperf
dataset_path: /gcs-pvc/qinwen/data
adam_eps: 1e-5
enable_checkpointing: True
load_parameters_path: /ckpt-pvc/qinwen/checkpoint 
attention: cudnn_flash_te
remat_policy: save_qkv_proj
use_iota_embed: true
logits_dot_in_fp32: false
quantization: fp8
enable_goodput_recording: false
monitor_goodput: false
save_config_to_gcs: true
enable_step_logging: true
enable_metric_writing: true
target_eval_loss: 5.6
steps: 350
data_shuffle_seed: 4875
